name: autosend

on:
  schedule:
    - cron: "*/2 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2.5.2
        with:
          node-version: "20.3.1"

      - name: Create env file
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Installing dependencies
        run: yarn install

      - name: Run the project
        run: node main.js
